name: Release (main)

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Bump version and release
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.do_release.outputs.current_version }}

    steps:
      - uses: https://code.forgejo.org/actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install helper-script
        run: |
          curl --fail -sS -o /usr/local/bin/forgejo-curl.sh "https://git.h.oluflorenzen.de/mirrors/forgejo-curl/raw/branch/main/forgejo-curl.sh" && chmod +x /usr/local/bin/forgejo-curl.sh
          export PATH=/usr/local/bin:$PATH
          forgejo-curl.sh --token "${{ env.FORGEJO_TOKEN }}" login ${{ env.FORGEJO_SERVER_URL }}
          forgejo-curl.sh api_json ${{ env.FORGEJO_SERVER_URL }}/api/v1/user

      - name: Configure Git User
        uses: https://git.h.oluflorenzen.de/mirrors/codeberg.PurpleBooth.common-pipelines/actions/configure-git-user@main

      - name: Release with cocogitto
        id: do_release
        uses: https://git.h.oluflorenzen.de/mirrors/codeberg.PurpleBooth.common-pipelines/actions/release-with-cog@main
