name: GO lint & test

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: node:24-bookworm

    steps:
      - uses: https://code.forgejo.org/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        uses: https://github.com/actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Install just
        uses: https://codeberg.org/FelixSchwarz/setup-just@v4.0.0-codeberg

      - name: Download dependencies
        run: go mod download

      - name: Lint
        run: just golangci-lint

      - name: Test
        run: just test-unit

      - name: Build (linux/amd64)
        run: just build-linux-amd64
