name: GO lint & test

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: node:24-bookworm@sha256:5711a0d445a1af54af9589066c646df387d1831a608226f4cd694fc59e745059

    steps:
      - uses: https://code.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: https://github.com/actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Install just
        uses: https://codeberg.org/FelixSchwarz/setup-just@v4.0.0-codeberg

      - name: Download dependencies
        run: go mod download

      - name: Lint
        run: just golangci-lint

      - name: Test
        run: just test-unit

      - name: Build (linux/amd64)
        run: just build-linux-amd64
