name: GO lint & test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25-bookworm

    steps:
      - uses: https://code.forgejo.org/actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v6.0.2

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -tags timetzdata ./...

  test:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: golang:1.25-bookworm

    steps:
      - uses: https://code.forgejo.org/actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v6.0.2

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test ./... -v

  lint:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:latest

    steps:
      - uses: https://code.forgejo.org/actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v6.0.2

      - name: Lint
        run: golangci-lint run --timeout=10m --config=.golangci.yml
