name: PR Info

on:
  pull_request:
    branches:
      - main

jobs:
  release-info:
    name: Changelog preview
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.release.outputs.current_version }}
      next_dev_version: ${{ steps.release.outputs.next_dev_version }}
      changelog: ${{ steps.release.outputs.changelog }}

    steps:
      - uses: https://code.forgejo.org/actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v6.0.2
        with:
          fetch-tags: true
          #fetch-depth: 30

      - name: Get release info
        id: release
        uses: https://git.h.oluflorenzen.de/finkregh/actions/actions/release-with-cog@main
        #with:
        #  dry-run: "true"
        #  dev_version_suffix: "_dev"

      - name: Show changelog preview
        run: |
          echo "## 📋 Next version: ${{ steps.release.outputs.current_version }}"
          echo ""
          echo "${{ steps.release.outputs.changelog }}"
